import org.openapitools.generator.gradle.plugin.tasks.GenerateTask

plugins {
    id 'java'
    id 'org.springframework.boot' version '4.0.6'
    id 'org.openapi.generator' version '7.22.0'
    id 'io.spring.dependency-management' version '1.1.7'
}

group 'com.carscompany.cars'
version '1.0'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}


//Configuration and tasks necessary for the integration tests

configurations {
    integrationTestRuntimeOnly { extendsFrom testRuntimeOnly }
    integrationTestImplementation { extendsFrom testImplementation }
}

sourceSets {
    integrationTest {
        java {
            srcDir 'src/integrationTest/java'
            compileClasspath += main.output + test.output
            runtimeClasspath += main.output + test.output
        }
    }
}

tasks.register('integrationTest', Test) {
    include 'com/carscompany/cars/api/CarsApiImplIntegrationTest.class'
    testClassesDirs = sourceSets.integrationTest.output.classesDirs
    classpath = sourceSets.integrationTest.runtimeClasspath
    useJUnitPlatform()
}


dependencies {

    compileOnly 'org.projectlombok:lombok'

    annotationProcessor 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok-mapstruct-binding:0.2.0'
    annotationProcessor 'org.mapstruct:mapstruct-processor:1.6.3'

    implementation 'org.mapstruct:mapstruct:1.6.3'

    implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-json'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.jspecify:jspecify'
    runtimeOnly 'com.h2database:h2'

    implementation 'org.openapitools:jackson-databind-nullable:0.2.10'
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.17.1'

    testImplementation 'org.mockito:mockito-junit-jupiter'
    testImplementation 'org.junit.jupiter:junit-jupiter-api'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testImplementation 'io.rest-assured:rest-assured:6.0.0'
    testImplementation 'org.hamcrest:hamcrest:3.0'
}

test {
    useJUnitPlatform()
}

bootJar {
    archiveFileName = "app.jar"
}


//Configuration and tasks necessary for the creation of the API server stub.

sourceSets.main.java.srcDirs += layout.buildDirectory.dir("generated/cars-api-v1/src/main/java").get()

springBoot {
    mainClass = 'com.carscompany.cars.CarsApplication'
}

tasks.register('buildcarsCarsApi', GenerateTask) {
    generatorName = "spring"
    inputSpec = layout.projectDirectory.file("src/main/resources/cars-api-v1.yaml")
    outputDir = layout.buildDirectory.dir("generated/cars-api-v1").get()

    packageName = project.group
    modelPackage = project.group + ".apimodel"
    apiPackage = project.group + ".api"
    configOptions = [
            delegatePattern      : "true",
            useSpringBoot3       : "true",
            documentationProvider: "none"
    ]
}

compileJava.dependsOn buildcarsCarsApi